services:
  airflow:
    image: ghcr.io/marcow03/gizstrom/airflow:latest
    # for testing, we can build the image locally
    # build: .
    depends_on:
      rustfs:
        condition: service_healthy
      create-buckets:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ../../src/dags:/opt/airflow/dags
      - ../../data/airflow/data:/opt/airflow/data
      - ../../data/airflow/data/logs:/opt/airflow/logs
      - ../../data/airflow/data/config:/opt/airflow/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: True
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: True
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DATA_BUCKET: ${DATA_BUCKET}
      FEAST_REGISTRY_DESTINATION: ${FEAST_REGISTRY_DESTINATION}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
    networks:
      - production
    command: standalone
    user: "50000:0"
    working_dir: /opt/airflow
