services:
  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    volumes:
      - ../../data/feast/redis:/data
    environment:
      FEAST_REDIS_PASSWORD: ${FEAST_REDIS_PASSWORD}
    networks:
      - production
    command: redis-server --save 20 1 --loglevel warning --requirepass ${FEAST_REDIS_PASSWORD}

  feast-ui:
    image: ghcr.io/marcow03/gizstrom/feast-ui
    build: .
    restart: unless-stopped
    depends_on:
      rustfs:
        condition: service_healthy
      redis:
        condition: service_started
      create-buckets:
        condition: service_completed_successfully
    ports:
      - "8088:8088"
    volumes:
      - ../../src/pipelines/pipelines/feature_repo:/opt/feast/feature_repo
    environment:
      FEAST_REGISTRY_DESTINATION: ${FEAST_REGISTRY_DESTINATION}
      FEAST_REDIS_PORT: ${FEAST_REDIS_PORT}
      FEAST_REDIS_HOST: ${FEAST_REDIS_HOST}
      FEAST_REDIS_PASSWORD: ${FEAST_REDIS_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ADDRESSING_STYLE: path
      FEAST_S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
    networks:
      - production
      - development
    command: "feast ui --host 0.0.0.0 --port 8088"
    working_dir: /opt/feast/feature_repo